[workspace]
members = [
    "crates/spindle",
    "crates/spindle-extension-sdk",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/shuymn/spindle"

[workspace.dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.10.9"
spindle-extension-sdk = { path = "crates/spindle-extension-sdk" }
thiserror = "2.0.18"
uuid = { version = "1.12.1", default-features = false, features = ["v7", "std", "rng"] }

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
infinite_loop = "deny"
map_err_ignore = "deny"
panic = "deny"
str_to_string = "deny"
implicit_clone = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
