use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::{SpindleError, now_unix_ms, validate_json_object, validate_name, validate_subject};

/// Append-only event envelope used by spindle clients and extensions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Event {
    /// Stable event identifier generated by the local process.
    pub id: String,
    /// Event type, for example `agent.status.changed`.
    #[serde(rename = "type")]
    pub kind: String,
    /// Logical producer, for example `codex-hook` or `sketchybar-extension`.
    pub source: String,
    /// Optional object this event describes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Event time as milliseconds since Unix epoch.
    pub time_unix_ms: u64,
    /// Event payload. The kernel stores it but does not interpret it.
    pub data: Value,
}

impl Event {
    /// Start building a validated event.
    #[must_use]
    pub fn builder(kind: String, source: String) -> EventBuilder {
        EventBuilder {
            kind,
            source,
            subject: None,
            data: Value::Object(serde_json::Map::new()),
        }
    }
}

/// Builder for [`Event`].
#[derive(Debug, Clone)]
pub struct EventBuilder {
    kind: String,
    source: String,
    subject: Option<String>,
    data: Value,
}

impl EventBuilder {
    /// Attach an optional subject.
    #[must_use]
    pub fn subject(mut self, subject: Option<String>) -> Self {
        self.subject = subject;
        self
    }

    /// Attach event data.
    #[must_use]
    pub fn data(mut self, data: Value) -> Self {
        self.data = data;
        self
    }

    /// Validate and build the event.
    ///
    /// # Errors
    ///
    /// Returns an error if required fields are empty, contain control
    /// characters, or the system clock cannot produce a Unix timestamp.
    pub fn build(self) -> Result<Event, SpindleError> {
        validate_name("type", &self.kind)?;
        validate_name("source", &self.source)?;
        if let Some(subject) = &self.subject {
            validate_subject("subject", subject)?;
        }
        validate_json_object("data", &self.data)?;

        let time_unix_ms = now_unix_ms()?;

        Ok(Event {
            id: uuid_v7_string(),
            kind: self.kind,
            source: self.source,
            subject: self.subject,
            time_unix_ms,
            data: self.data,
        })
    }
}

/// Action request recorded by the kernel before any extension handles it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionRequest {
    /// Action name, for example `aerospace.workspace.focus`.
    pub action: String,
    /// Logical requester.
    pub requested_by: String,
    /// Capabilities granted to this dispatch request.
    pub capabilities: Vec<String>,
    /// Action arguments.
    pub args: Value,
    /// Continuation provenance for deferred extension work.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<ContinuationAudit>,
}

/// Continuation provenance stamped into deferred action audit events.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContinuationAudit {
    /// Opaque continuation identifier.
    pub id: String,
    /// Extension that received the continuation.
    pub extension: String,
    /// Original action that received the continuation.
    pub action: String,
}

impl ActionRequest {
    /// Convert this request into an append-only event.
    ///
    /// # Errors
    ///
    /// Returns an error if the action name, requester, or capabilities are
    /// invalid, or if JSON serialization fails.
    pub fn into_event(self) -> Result<Event, SpindleError> {
        validate_name("action", &self.action)?;
        validate_name("requested_by", &self.requested_by)?;
        for capability in &self.capabilities {
            validate_name("capability", capability)?;
        }
        validate_json_object("args", &self.args)?;

        let data = serde_json::to_value(&self)?;
        Event::builder(String::from("action.requested"), self.requested_by)
            .data(data)
            .build()
    }
}

/// Query filters for reading events from the local log.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct EventFilter {
    /// Optional event type filter.
    pub kind: Option<String>,
    /// Optional source filter.
    pub source: Option<String>,
    /// Maximum number of events to return from the tail of the matched set.
    pub limit: Option<usize>,
}

impl EventFilter {
    /// Return true when the event matches this filter.
    #[must_use]
    pub fn matches(&self, event: &Event) -> bool {
        let kind_matches = self.kind.as_ref().is_none_or(|kind| kind == &event.kind);
        let source_matches = self
            .source
            .as_ref()
            .is_none_or(|source| source == &event.source);
        kind_matches && source_matches
    }
}

fn uuid_v7_string() -> String {
    uuid::Uuid::now_v7().to_string()
}

#[cfg(test)]
mod tests {
    use std::{collections::BTreeSet, thread};

    use serde_json::json;

    use super::*;

    #[test]
    fn event_builder_rejects_empty_type() {
        let result = Event::builder(String::new(), String::from("test")).build();
        assert!(result.is_err());
    }

    #[test]
    fn event_builder_generates_uuid_identifier() -> Result<(), SpindleError> {
        let event = Event::builder(String::from("test.changed"), String::from("test")).build()?;

        assert_eq!(event.id.len(), 36);
        assert_eq!(&event.id[8..9], "-");
        assert_eq!(&event.id[13..14], "-");
        assert_eq!(&event.id[18..19], "-");
        assert_eq!(&event.id[23..24], "-");
        assert_eq!(&event.id[14..15], "7");
        let parsed =
            uuid::Uuid::parse_str(&event.id).map_err(|_source| SpindleError::InvalidField {
                field: "id",
                reason: "must parse as UUID",
            })?;
        assert_eq!(parsed.to_string(), event.id);

        let variant = &event.id[19..20];
        assert!(matches!(variant, "8" | "9" | "a" | "b"));
        Ok(())
    }

    #[test]
    fn event_builder_generates_unique_ids_across_threads() -> Result<(), SpindleError> {
        let handles = (0..8)
            .map(|_thread| {
                thread::spawn(|| -> Result<Vec<String>, SpindleError> {
                    let mut ids = Vec::new();
                    for _ in 0..128 {
                        ids.push(
                            Event::builder(String::from("test.changed"), String::from("test"))
                                .build()?
                                .id,
                        );
                    }
                    Ok(ids)
                })
            })
            .collect::<Vec<_>>();

        let mut ids = BTreeSet::new();
        for handle in handles {
            let thread_ids = handle
                .join()
                .map_err(|_payload| SpindleError::InvalidField {
                    field: "thread",
                    reason: "panicked",
                })??;
            for id in thread_ids {
                ids.insert(id);
            }
        }

        assert_eq!(ids.len(), 1024);
        Ok(())
    }

    #[test]
    fn action_request_becomes_event() -> Result<(), SpindleError> {
        let event = ActionRequest {
            action: String::from("aerospace.workspace.focus"),
            requested_by: String::from("raycast"),
            capabilities: vec![String::from("aerospace.window.control")],
            args: json!({ "name": "dev" }),
            continuation: None,
        }
        .into_event()?;

        assert_eq!(event.kind, "action.requested");
        assert_eq!(event.source, "raycast");
        assert_eq!(event.data["action"], "aerospace.workspace.focus");
        Ok(())
    }
}
