use std::{
    process,
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::{SpindleError, validate_token};

/// Append-only event envelope used by spindle clients and extensions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Event {
    /// Stable event identifier generated by the local process.
    pub id: String,
    /// Event type, for example `agent.status.changed`.
    #[serde(rename = "type")]
    pub kind: String,
    /// Logical producer, for example `codex-hook` or `sketchybar-extension`.
    pub source: String,
    /// Optional object this event describes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Event time as milliseconds since Unix epoch.
    pub time_unix_ms: u128,
    /// Event payload. The kernel stores it but does not interpret it.
    pub data: Value,
}

impl Event {
    /// Start building a validated event.
    #[must_use]
    pub fn builder(kind: String, source: String) -> EventBuilder {
        EventBuilder {
            kind,
            source,
            subject: None,
            data: Value::Object(serde_json::Map::new()),
        }
    }
}

/// Builder for [`Event`].
#[derive(Debug, Clone)]
pub struct EventBuilder {
    kind: String,
    source: String,
    subject: Option<String>,
    data: Value,
}

impl EventBuilder {
    /// Attach an optional subject.
    #[must_use]
    pub fn subject(mut self, subject: Option<String>) -> Self {
        self.subject = subject;
        self
    }

    /// Attach event data.
    #[must_use]
    pub fn data(mut self, data: Value) -> Self {
        self.data = data;
        self
    }

    /// Validate and build the event.
    ///
    /// # Errors
    ///
    /// Returns an error if required fields are empty, contain control
    /// characters, or the system clock cannot produce a Unix timestamp.
    pub fn build(self) -> Result<Event, SpindleError> {
        validate_token("type", &self.kind)?;
        validate_token("source", &self.source)?;
        if let Some(subject) = &self.subject {
            validate_token("subject", subject)?;
        }

        let time_unix_ms = now_unix_ms()?;

        Ok(Event {
            id: uuid_v7_string(time_unix_ms),
            kind: self.kind,
            source: self.source,
            subject: self.subject,
            time_unix_ms,
            data: self.data,
        })
    }
}

/// Action request recorded by the kernel before any extension handles it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionRequest {
    /// Action name, for example `aerospace.workspace.focus`.
    pub action: String,
    /// Logical requester.
    pub requested_by: String,
    /// Capabilities granted to this dispatch request.
    pub capabilities: Vec<String>,
    /// Action arguments.
    pub args: Value,
}

impl ActionRequest {
    /// Convert this request into an append-only event.
    ///
    /// # Errors
    ///
    /// Returns an error if the action name, requester, or capabilities are
    /// invalid, or if JSON serialization fails.
    pub fn into_event(self) -> Result<Event, SpindleError> {
        validate_token("action", &self.action)?;
        validate_token("requested_by", &self.requested_by)?;
        for capability in &self.capabilities {
            validate_token("capability", capability)?;
        }

        let data = serde_json::to_value(&self)?;
        Event::builder(String::from("action.requested"), self.requested_by)
            .data(data)
            .build()
    }
}

/// Query filters for reading events from the local log.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct EventFilter {
    /// Optional event type filter.
    pub kind: Option<String>,
    /// Optional source filter.
    pub source: Option<String>,
    /// Maximum number of events to return from the tail of the matched set.
    pub limit: Option<usize>,
}

impl EventFilter {
    /// Return true when the event matches this filter.
    #[must_use]
    pub fn matches(&self, event: &Event) -> bool {
        let kind_matches = self.kind.as_ref().is_none_or(|kind| kind == &event.kind);
        let source_matches = self
            .source
            .as_ref()
            .is_none_or(|source| source == &event.source);
        kind_matches && source_matches
    }
}

static NEXT_EVENT_ID: AtomicU64 = AtomicU64::new(0);

fn now_unix_ms() -> Result<u128, SpindleError> {
    Ok(SystemTime::now().duration_since(UNIX_EPOCH)?.as_millis())
}

fn uuid_v7_string(time_unix_ms: u128) -> String {
    let timestamp = u64::try_from(time_unix_ms).unwrap_or(u64::MAX) & 0xffff_ffff_ffff;
    let counter = NEXT_EVENT_ID.fetch_add(1, Ordering::Relaxed);
    let entropy = counter ^ u64::from(process::id()).rotate_left(17) ^ timestamp.rotate_left(11);
    let rand_a = u16::try_from((entropy >> 52) & 0x0fff).unwrap_or(0);
    let rand_b = entropy & 0x3fff_ffff_ffff_ffff;

    let group1 = u32::try_from(timestamp >> 16).unwrap_or(u32::MAX);
    let group2 = u16::try_from(timestamp & 0xffff).unwrap_or(u16::MAX);
    let group3 = 0x7000 | rand_a;
    let group4 = 0x8000 | u16::try_from(rand_b >> 48).unwrap_or(0);
    let group5 = rand_b & 0x0000_ffff_ffff_ffff;

    format!("{group1:08x}-{group2:04x}-{group3:04x}-{group4:04x}-{group5:012x}")
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn event_builder_rejects_empty_type() {
        let result = Event::builder(String::new(), String::from("test")).build();
        assert!(result.is_err());
    }

    #[test]
    fn event_builder_generates_uuid_identifier() -> Result<(), SpindleError> {
        let event = Event::builder(String::from("test.changed"), String::from("test")).build()?;

        assert_eq!(event.id.len(), 36);
        assert_eq!(&event.id[8..9], "-");
        assert_eq!(&event.id[13..14], "-");
        assert_eq!(&event.id[18..19], "-");
        assert_eq!(&event.id[23..24], "-");
        assert_eq!(&event.id[14..15], "7");

        let variant = &event.id[19..20];
        assert!(matches!(variant, "8" | "9" | "a" | "b"));
        Ok(())
    }

    #[test]
    fn action_request_becomes_event() -> Result<(), SpindleError> {
        let event = ActionRequest {
            action: String::from("aerospace.workspace.focus"),
            requested_by: String::from("raycast"),
            capabilities: vec![String::from("aerospace.window.control")],
            args: json!({ "name": "dev" }),
        }
        .into_event()?;

        assert_eq!(event.kind, "action.requested");
        assert_eq!(event.source, "raycast");
        assert_eq!(event.data["action"], "aerospace.workspace.focus");
        Ok(())
    }
}
